Repository UnirCs/DWFS-PER8408-2324, pull requests merged in 2023-11, with the labels that each got.

#8 Creación de espacio de trabajo
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/github.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/gmail.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/linkedin.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/profile.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/ubicacion.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/web.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/assets/whatsapp.png
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/index.html
  Tema_1/Alejandro_Rodriguez_Benalcazar/CV/styles.css
  Tema_1/Alejandro_Rodriguez_Benalcazar/Cinema/index.html
  Tema_1/Alejandro_Rodriguez_Benalcazar/Cinema/styles.css
Labels: Se necesitan cambios

#29 Ejercicios Tema 1
  Tema_1/AlanGuijarro/cinema/index.html
  Tema_1/AlanGuijarro/cinema/styles.css
  Tema_1/AlanGuijarro/cv/Fotografía.jpg
  Tema_1/AlanGuijarro/cv/index.html
  Tema_1/AlanGuijarro/cv/styles.css
Labels: Se necesitan cambios

#38 Entrega actividades opcionales Tema 2
  Tema_2/Salva Roca/Cinema/cinema.js
  Tema_2/Salva Roca/filtros/actividad.js
Labels: Se necesitan cambios

#45 Ejercicio CV
  Tema_1/Emiliano_Albamonte_Barber/cinema/index.html
  Tema_1/Emiliano_Albamonte_Barber/cinema/styles.css
  Tema_1/Emiliano_Albamonte_Barber/cv/index.html
  Tema_1/Emiliano_Albamonte_Barber/cv/styles.css
Labels: Se necesitan cambios

#60 Ejercicio Cinema
  Tema_1/Kelvin_Moquete/CV/index.html
  Tema_1/Kelvin_Moquete/CV/styles.css
  Tema_1/Kelvin_Moquete/Cinema/index.html
  Tema_1/Kelvin_Moquete/Cinema/styles.css
Labels: PR Incorrecta

#58 Ejercicios Tema 2
  Tema_2/Lucia Rodriguez Perez/Cinema/cinema.js
  Tema_2/Lucia Rodriguez Perez/Filter/actividad.js
Labels: Se necesitan cambios, Propuesta de mejora

#62 Tema 2: Actividad cinema e imágenes
  Tema_2/Andrea_Sucre/Cinema/cinema.js
  Tema_2/Andrea_Sucre/Filtros/actividad.js
Labels: Se necesitan cambios, Propuesta de mejora

#52 Ejercicios Tema 2
  Tema_2/Jose Manuel Frias/cinema/cinema.js
  Tema_2/Jose Manuel Frias/filtros/actividad.js
Labels: Se necesitan cambios

#66 Ejercicios Tema 2
  Tema_2/GorkaGonzalezGomez/cinema/cinema.js
  Tema_2/GorkaGonzalezGomez/filtros/actividad.js
Labels: PR Incorrecta

#74 Ejercicios tema 2 María Cifuentes
  Tema_2/Maria Cifuentes Cabañero/cinema/cinema.js
  Tema_2/Maria Cifuentes Cabañero/filtros/actividad.js
Labels: Propuesta de mejora

#77 Cinema y Filtros
  Tema_2/Alejandro_Rodriguez_Benalcazar/cinema/cinema.js
  Tema_2/Alejandro_Rodriguez_Benalcazar/filtros/actividad.js
Labels: Propuesta de mejora

#54 ejercicio filtros hecho
  Tema_2/Emiliano_Albamonte_Barber/cinema/cinema.js
  Tema_2/Emiliano_Albamonte_Barber/filtros/actividad.js
Labels: Se necesitan cambios

#59 Tema 2
  Tema_2/Erick Altamirano/Cinema/cinema.js
  Tema_2/Erick Altamirano/Filtros/actividad.js
Labels: Se necesitan cambios, Propuesta de mejora

#64 Tema1 - CV Task
  Tema_1/Javier_Belmonte_Romero/cv/index.html
  Tema_1/Javier_Belmonte_Romero/cv/perfil.png
  Tema_1/Javier_Belmonte_Romero/cv/styles.css
  Tema_2/Javier_Belmonte_Romero/cinema/cinema.js
Labels: PR Incorrecta, Se necesitan cambios, Propuesta de mejora

#72 Ejercicios Tema 1 Albert Escoté Alvarez
  Tema_1/albertescotealvarez/cinema/index.html
  Tema_1/albertescotealvarez/cinema/styles.css
  Tema_1/albertescotealvarez/cv/index.html
  Tema_1/albertescotealvarez/cv/styles.css
Labels: Se necesitan cambios

#82 Ejercicios Tema 2 && Tema 3
  Tema_2/Richar_Cangui/Cinema/cinema.js
  Tema_2/Richar_Cangui/filtros/actividad.js
  Tema_3/Richar_Cangui/Chuck/index.html
  Tema_3/Richar_Cangui/Chuck/style.css
  Tema_3/Richar_Cangui/Cinema/cinema.js
  Tema_3/Richar_Cangui/Cinema/index.html
  Tema_3/Richar_Cangui/Cinema/styles.css
Labels: PR Incorrecta

#87 Ejercicios voluntarios tema 2 y 3
  Tema_2/Guillermo_Marcos_García/cinema/cinema.js
  Tema_2/Guillermo_Marcos_García/filtros/actividad.js
  Tema_3/Guillermo_Marcos_García/Chuck/css/styles.css
  Tema_3/Guillermo_Marcos_García/Chuck/images/logo.png
  Tema_3/Guillermo_Marcos_García/Chuck/index.html
  Tema_3/Guillermo_Marcos_García/Cinema/cinema.js
  Tema_3/Guillermo_Marcos_García/Cinema/css/styles.css
  Tema_3/Guillermo_Marcos_García/Cinema/index.html
Labels: Se necesitan cambios

#99 Se dejan Archivos de ejemplo en Rama Master como estaban
  Tema_1/Breriner Medina Villero/CINEMA/estilos.css
  Tema_1/Breriner Medina Villero/CINEMA/index.html
  Tema_1/Breriner Medina Villero/CV/Messi.jpg
  Tema_1/Breriner Medina Villero/CV/Messi2.jpg
  Tema_1/Breriner Medina Villero/CV/Messi3.jpg
  Tema_1/Breriner Medina Villero/CV/Messi4.jpg
  Tema_1/Breriner Medina Villero/CV/estilos.css
  Tema_1/Breriner Medina Villero/CV/index.html
  Tema_2/Breiner Medina Villero/CINEMA/cinema.js
Labels: PR Incorrecta

#91 Tema 2 y Tema 3
  Tema_2/Javier_Cantalapiedra_Artiaga/Cinema/cinema.js
  Tema_2/Javier_Cantalapiedra_Artiaga/filtros/actividad.js
  Tema_3/Javier_Cantalapiedra_Artiaga/Chuck/index.html
  Tema_3/Javier_Cantalapiedra_Artiaga/Chuck/script.js
  Tema_3/Javier_Cantalapiedra_Artiaga/Chuck/styles.css
  Tema_3/Javier_Cantalapiedra_Artiaga/Cinema/cinema.js
  Tema_3/Javier_Cantalapiedra_Artiaga/Cinema/index.html
  Tema_3/Javier_Cantalapiedra_Artiaga/Cinema/styles.css
Labels: Se necesitan cambios

#129 Tema 4 Ejercicio
  Tema_4/Jesus Sanchez Alvarez/Cinema/Respuesta.md
  Tema_4/Jesus Sanchez Alvarez/Cinema/cinema.css
  Tema_4/Jesus Sanchez Alvarez/Cinema/cinema.html
  Tema_4/Jesus Sanchez Alvarez/Cinema/cinema.js
  Tema_4/Jesus Sanchez Alvarez/Cinema/index.html
  Tema_4/Jesus Sanchez Alvarez/Cinema/script.js
  Tema_4/Jesus Sanchez Alvarez/Cinema/styles.css
Labels: Propuesta de mejora

#124 master
  Tema_2/CarlosAugustoNoleMachaca/.gitignore
  Tema_2/CarlosAugustoNoleMachaca/Cinema/Cinema.js
  Tema_2/CarlosAugustoNoleMachaca/filtros/ImageHandler.js
  Tema_2/CarlosAugustoNoleMachaca/filtros/actividad.js
  Tema_2/CarlosAugustoNoleMachaca/filtros/input/cat.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/input/dog.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/input/tucan.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/merged.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_black_and_white.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_blue.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_dimed.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_green.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_grey.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_inverse.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_red.jpg
  Tema_2/CarlosAugustoNoleMachaca/filtros/output/expected/tucan_scale_down.jpg
Labels: PR Incorrecta, Se necesitan cambios

#109 Trabajo tema 2 - Jose Luis Gomez C.
  Tema_2/JoseLuisGomez/Cinema/cinema.js
  Tema_2/JoseLuisGomez/filtros/actividad.js
Labels: Se necesitan cambios

#123 Cambios Jose_luis_bautista_beltran
  Tema_1/Jose_luis_Bautista_Beltran/CV/foto.png
  Tema_1/Jose_luis_Bautista_Beltran/CV/index.html
  Tema_1/Jose_luis_Bautista_Beltran/CV/styles.css
  Tema_1/Jose_luis_Bautista_Beltran/Cinema/index.html
  Tema_1/Jose_luis_Bautista_Beltran/Cinema/styles.css
  Tema_2/00_Resources/filtros/actividad.js
  Tema_2/Jose_Luis_Bautista_Beltran/cinema/cinema.js
  Tema_2/Jose_Luis_Bautista_Beltran/filtros/actividad.js
  Tema_3/Jose_Luis_Bautista_Beltran/Chuck/index.html
  Tema_3/Jose_Luis_Bautista_Beltran/Chuck/styles.css
  Tema_3/Jose_Luis_Bautista_Beltran/Cinema/cinema.js
  Tema_3/Jose_Luis_Bautista_Beltran/Cinema/index.html
  Tema_3/Jose_Luis_Bautista_Beltran/Cinema/styles.css
Labels: PR Incorrecta, Se necesitan cambios

#127 Ejercicio Tema 4
  Tema_4/Jose Manuel Frias/cinema/cinema.css
  Tema_4/Jose Manuel Frias/cinema/cinema.html
  Tema_4/Jose Manuel Frias/cinema/cinema.js
  Tema_4/Jose Manuel Frias/cinema/login.css
  Tema_4/Jose Manuel Frias/cinema/login.html
  Tema_4/Jose Manuel Frias/cinema/login.js
Labels: Propuesta de mejora
