Repository UnirCs/DWFS-PER8408-2324, pull requests merged in 2023-12, with the labels that each got.

#156 Ajuste TEMA 1
  Tema_1/Julian_Rojas/cv/img/direccion.png
  Tema_1/Julian_Rojas/cv/img/email.png
  Tema_1/Julian_Rojas/cv/img/telefono.png
  Tema_1/Julian_Rojas/cv/index.html
  Tema_1/Julian_Rojas/cv/styles.css
Labels: PR Incorrecta

#178 EJERCICIO 5 CINEMA
  Tema_2/00_Resources/filtros/actividad.js
  Tema_3/RODRIGUEZ FERNANDO/Chuck/index.html
  Tema_3/RODRIGUEZ FERNANDO/Chuck/styless.css
  Tema_3/RODRIGUEZ FERNANDO/cinema/cinema.js
  Tema_3/RODRIGUEZ FERNANDO/cinema/index.html
  Tema_3/RODRIGUEZ FERNANDO/cinema/styles.css
  Tema_5/RODRIGUEZ _FERNANDO/cienma/.gitignore
  Tema_5/RODRIGUEZ _FERNANDO/cienma/README.md
  Tema_5/RODRIGUEZ _FERNANDO/cienma/package-lock.json
  Tema_5/RODRIGUEZ _FERNANDO/cienma/package.json
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/favicon.ico
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/index.html
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/logo192.png
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/logo512.png
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/manifest.json
  Tema_5/RODRIGUEZ _FERNANDO/cienma/public/robots.txt
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/App.css
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/App.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/App.test.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/components/gridMovies.css
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/components/gridMovies.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/components/movie.css
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/components/movie.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/index.css
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/index.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/reportWebVitals.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/setupTests.js
  Tema_5/RODRIGUEZ _FERNANDO/cienma/src/utils/moviesCatalog.js
  Tema_5/RODRIGUEZ _FERNANDO/urlVercel.txt
Labels: PR Incorrecta

#198 Tema_4 Ejercicio Javier Belmonte
  Tema_4/Javier_Belmonte_Romero/cinema/cinema.css
  Tema_4/Javier_Belmonte_Romero/cinema/cinema.html
  Tema_4/Javier_Belmonte_Romero/cinema/cinema.js
  Tema_4/Javier_Belmonte_Romero/cinema/registro.css
  Tema_4/Javier_Belmonte_Romero/cinema/registro.html
  Tema_4/Javier_Belmonte_Romero/cinema/registro.js
  Tema_4/Javier_Belmonte_Romero/cinema/screen.png
  Tema_5/Javier_Belmonte_Romero/cinema/.gitignore
  Tema_5/Javier_Belmonte_Romero/cinema/README.md
  Tema_5/Javier_Belmonte_Romero/cinema/package-lock.json
  Tema_5/Javier_Belmonte_Romero/cinema/package.json
  Tema_5/Javier_Belmonte_Romero/cinema/public/favicon.ico
  Tema_5/Javier_Belmonte_Romero/cinema/public/index.html
  Tema_5/Javier_Belmonte_Romero/cinema/public/logo192.png
  Tema_5/Javier_Belmonte_Romero/cinema/public/logo512.png
  Tema_5/Javier_Belmonte_Romero/cinema/public/manifest.json
  Tema_5/Javier_Belmonte_Romero/cinema/public/robots.txt
  Tema_5/Javier_Belmonte_Romero/cinema/src/components/Footer.js
  Tema_5/Javier_Belmonte_Romero/cinema/src/components/Header.js
  Tema_5/Javier_Belmonte_Romero/cinema/src/components/Movie.js
  Tema_5/Javier_Belmonte_Romero/cinema/src/components/MovieList.js
  Tema_5/Javier_Belmonte_Romero/cinema/src/index.css
  Tema_5/Javier_Belmonte_Romero/cinema/src/index.js
  Tema_5/Javier_Belmonte_Romero/cinema/src/logo.svg
  Tema_5/Javier_Belmonte_Romero/cinema/src/styles/HeaderFooter.css
  Tema_5/Javier_Belmonte_Romero/cinema/src/styles/MovieCard.css
  Tema_5/Javier_Belmonte_Romero/cinema/src/styles/MovieList.css
  Tema_5/Javier_Belmonte_Romero/cinema/src/views/Overview.js
  Tema_5/Javier_Belmonte_Romero/urlVercel.txt
Labels: Ejercicio Incompleto

#172 Ejercicio Tema 5. Cartelera
  Tema_5/Jose Manuel Frias Salvachua/cinema/.gitignore
  Tema_5/Jose Manuel Frias Salvachua/cinema/README.md
  Tema_5/Jose Manuel Frias Salvachua/cinema/package-lock.json
  Tema_5/Jose Manuel Frias Salvachua/cinema/package.json
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/favicon.ico
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/index.html
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/logo192.png
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/logo512.png
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/manifest.json
  Tema_5/Jose Manuel Frias Salvachua/cinema/public/robots.txt
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/App.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/App.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/App.test.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/components/Footer.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/components/Header.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/components/Movie.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/components/MovieList.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/index.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/index.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/logo.svg
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/reportWebVitals.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/setupTests.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/styles/footer.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/styles/header.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/styles/movie.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/styles/movieList.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/styles/styles.css
  Tema_5/Jose Manuel Frias Salvachua/cinema/src/views/Overview.js
  Tema_5/Jose Manuel Frias Salvachua/cinema/vercelURL.txt
  Tema_5/Jose Manuel Frias Salvachua/package-lock.json
  Tema_5/Jose Manuel Frias Salvachua/package.json
Labels: Ejercicio Incompleto

#212 Tarea 2,3 - Jonathan Mejia
  Tema_2/Jonathan_Vinicio_Mejia_Salazar/cinema/cinema.js
  Tema_2/Jonathan_Vinicio_Mejia_Salazar/filtros/actividad.js
  Tema_3/Jonathan_Vinicio_Mejia_Salazar/chuck/indext.html
  Tema_3/Jonathan_Vinicio_Mejia_Salazar/cinema/cinema.html
  Tema_3/Jonathan_Vinicio_Mejia_Salazar/cinema/script.js
  Tema_3/Jonathan_Vinicio_Mejia_Salazar/cinema/style.css
Labels: Se necesitan cambios
