Repository UnirCs/DWFS-PER8408-2324, pull requests merged in 2024-01, with the labels that each got.

#191 Tema 6
  Tema_6/Andrea_Sucre/Calculadora/Readme.md
  Tema_6/Andrea_Sucre/Cinema/Readme.md
  Tema_6/Andrea_Sucre/Hunde la flota/Readme.md
Labels: Se necesitan cambios

#197 Tarea del tema 5
  Tema_4/Alejandro_Rodriguez_Benalcazar/Cinema/cinema.css
  Tema_5/Alejandro_Rodriguez_Benalcazar/Enlace_Vercel.txt
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/.gitignore
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/README.md
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/package-lock.json
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/package.json
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/public/favicon.ico
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/public/index.html
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/muchachos.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/napoleon.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/noabrir.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/papaomama.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/venganza.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/assets/wonka.jpg
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/components/Footer.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/components/Header.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/components/Movie.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/components/MovieList.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/constants/images.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/constants/index.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/index.css
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/index.js
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/resources/movies.json
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/styles/styles.css
  Tema_5/Alejandro_Rodriguez_Benalcazar/cinema-react/src/views/Overview.js
Labels: Ejercicio Incompleto

#213 feat: ejercicios Tema6 Albert Escoté
  Tema_6/albertescotealvarez/Calculadora.md
  Tema_6/albertescotealvarez/Cinema.md
  Tema_6/albertescotealvarez/HundeLaFlota.md
Labels: Propuesta de mejora

#216 Entrega actividades opcionales tema 6
  Tema_6/Salva Roca/Calculadora.md
  Tema_6/Salva Roca/Cinema.md
  Tema_6/Salva Roca/HundeLaFlota.md
Labels: Se necesitan cambios

#220 Tema - 6
  Tema_6/Jesus Sanchez Alvarez/calculadora/calculadora.md
  Tema_6/Jesus Sanchez Alvarez/cine/cine.md
  Tema_6/Jesus Sanchez Alvarez/hunde la flota/hunde flota.md
Labels: Se necesitan cambios

#224 Ejercicios Tema 6
  Tema_6/Alicia_Rodriguez_Rodriguez/Calculadora.md
  Tema_6/Alicia_Rodriguez_Rodriguez/Cinema.md
  Tema_6/Alicia_Rodriguez_Rodriguez/Hundelaflota.md
Labels: Se necesitan cambios

#238 Actividad 2 gonzalo daquilema
  Tema_2/Gonzalo_Daquilema/cinema/cinema.js
  Tema_2/Gonzalo_Daquilema/filtros/actividad.js
  Tema_3/Gonzalo_Daquilema/chuck/index.html
  Tema_3/Gonzalo_Daquilema/chuck/styles.css
  Tema_3/Gonzalo_Daquilema/cinema/cinema.html
  Tema_3/Gonzalo_Daquilema/cinema/cinema.js
  Tema_3/Gonzalo_Daquilema/cinema/styles.css
Labels: Se necesitan cambios

#246 Entrega Tema 6 Calculadora y Cinema
  Tema_6/Sergio_Alvarez_Uribe/Calculadora.md
  Tema_6/Sergio_Alvarez_Uribe/Cinema.md
Labels: PR Incorrecta
